calibration:
  calib_distance_cm: 113
  calib_pixel_area: 10860
  min_area_threshold: 500
camera_controls:
  auto_exposure: 0
  auto_wb: 0
  brightness: 25
  contrast: 25
  exposure: 0
  wb_temperature: 0
hsv:
  h_max: 54
  h_min: 28
  s_max: 252
  s_min: 145
  v_max: 255
  v_min: 147
morphology:
  closing: 0
  dilation: 5
  erosion: 0
  opening: 0
