calibration:
  calib_distance_cm: 100
  calib_pixel_area: 38600
  min_area_threshold: 500
camera_controls:
  auto_exposure: 0
  auto_wb: 0
  brightness: 25
  contrast: 25
  exposure: 0
  wb_temperature: 0
hsv:
  h_max: 55
  h_min: 27
  s_max: 255
  s_min: 112
  v_max: 164
  v_min: 35
morphology:
  closing: 0
  dilation: 3
  erosion: 3
  opening: 0
