calibration_values:
  calib_distance_cm: 113
  calib_pixel_area: 10860
  min_area_threshold: 500
camera_controls:
  auto_exposure: 0
  auto_wb: 0
  brightness: 25
  contrast: 25
  exposure: 0
  wb_temperature: 0
control_mode: manual
hsv_values:
  h_max: 87
  h_min: 64
  s_max: 255
  s_min: 255
  v_max: 255
  v_min: 119
morphology_values:
  closing: 0
  dilation: 2
  erosion: 2
  opening: 0
pid_params:
  kd_arahhadap: 0.05
  kd_jarak: 0.05
  ki_arahhadap: 0.1
  ki_jarak: 0.1
  kp_arahhadap: 1.0
  kp_jarak: 1.0
  setpoint_jarak: 50.0
